### ISSUE TITLE
User management mvp / setup default users

### ISSUE THREAD

**Issue by Robrisi** [remlse/buenzlimarks#16]
users (strings) match  bookmarks.
get-request from api/user/  return bookmarks.
Default values

**Comment by remlse** [comment]
Amos made an article about exactly this:

https://fasterthanli.me/series/updating-fasterthanli-me-for-2022/part-6

**Comment by remlse** [comment]
For simplicity, requests are automatically authenticated as the default user when no cookie is set during development. This may be a little too simple. Let's require *some* cookie. For development with thunder client, one has to remember to set that cookie for the requests...
